### ISSUE TITLE
README example code gives error

### ISSUE THREAD

**Issue by lorenzwalthert** [rexyai/RestRserve#103]
Thanks for this useful package! I ran into an error from running the code in the README. Apparently, the method `new()` for `Logger` does not take a `file` argument:
``` r
library(RestRserve)
logger = Logger$new(level = TRACE, file = "")
#> Error in .subset2(public_bind_env, "initialize")(...): unused argument (file = "")
# ...
```

<sup>Created on 2019-11-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dselivanov** [comment]
Thanks for reporting. Hopefully this will soon fixed by merging `dev` branch.
