### ISSUE TITLE
Running under Kubernetes

### ISSUE THREAD

**Issue by Hong-Revo** [rexyai/RestRserve#105]
Hi all,

This is more an informational question. Is it possible/does it make sense to use this package inside a managed cluster, eg with Kubernetes? Since it appears that RestRServe can handle requests in parallel, and the point of K8s is to be able to scale to meet demand.

**Comment by dselivanov** [comment]
It does make sense indeed:
- scale beyond 1 node
- add redundancy for fault tolerance
