### ISSUE TITLE
Error when running example code.

### ISSUE THREAD

**Issue by BillyBonaros** [rexyai/RestRserve#106]
I'm trying to run the example but I get these errors: 

Error: object 'Application' not found
Error: object 'BackendRserve' not found

Then I saw that in the library there is no Application and BackendRserve function. 
I have installed it both with GitHub link and from remotes::install_github("rexyai/RestRserve") but i get the same errors.

**Comment by artemklevtsov** [comment]
Try dev branch.

**Comment by artemklevtsov** [comment]
Duplicate #103.

**Comment by dselivanov** [comment]
@BillyBonaros try `remotes::install_github("rexyai/RestRserve@dev")`

**Comment by BillyBonaros** [comment]
@dselivanov  Thanks!
