### ISSUE TITLE
Can you please add an example of POST method taking as input a json and outputs a json?

### ISSUE THREAD

**Issue by BillyBonaros** [rexyai/RestRserve#107]
For example as input a JSON {"a":"3","b":"4"} and to return as a result a json with the sum {"result","7"}.
I was trying a lot, but I didn't manage to do it. There is no POST example online.  The most difficult part is how to get as input the JSON and get the variables to work with.

**Comment by artemklevtsov** [comment]
You can start with examples include in the package. See [here](https://github.com/rexyai/RestRserve/tree/dev/inst/examples) for details.
