### ISSUE TITLE
Stop background process from R 

### ISSUE THREAD

**Issue by lorenzwalthert** [rexyai/RestRserve#110]
Would't it be nice to have: 

```r
backend <- BackendRserve$new()
backend$start(app, http_port = 1234, background = TRUE)
backend$stop()
```
?

**Comment by dselivanov** [comment]
In theory backend can start multiple applications. Having that in mind following `backend$stop()` doesn't look like generic solution... Suggestions welcome.

`backend$start()` invisibly returns `Rserve` process PID. In case of `Rserve` backend proper way of stopping a server will be 
1. kill process tree/group
1. kill `Rserve` master process 

Ideally in one shot: `pkill -P $PID && kill $PID`. This should not kill host R session which started the application.

**Comment by lorenzwalthert** [comment]
Cool. Thanks.

**Comment by dselivanov** [comment]
@lorenzwalthert it works, but not completely correct at the moment. It seems it doesn't properly kill processes which serve existing clients. It is a bit complicated to make it portable and work on OS X. More investigation might be needed in future.
