### ISSUE TITLE
pkill is Unix-alike-specific

### ISSUE THREAD

**Issue by Hong-Revo** [rexyai/RestRserve#113]
Hi,

I just noticed that in 3c56dcb0f75e57a825c099b7e6503dc8d3e018fa you use `pkill` to kill child processes. This is specific to Unices, so it won't work on Windows. I know that you recommend not using Windows, but it would still be nice if the package didn't have an enforced OS restriction.

The Win equivalent to `pkill` is `taskkill`; you can kill a process tree with `taskkill /F`. See SO answer here: https://stackoverflow.com/a/604545/474349

**Comment by dselivanov** [comment]
I'm windows you won't be able to fork, so option to kill app won't be
available. But thanks for keeping eyes.

**Comment by dselivanov** [comment]
@Hong-Revo closing?

**Comment by Hong-Revo** [comment]
Just had one more question: on Windows, is it still possible to do parallel processing, eg with PSOCK clusters rather than forks? Other than that, it sounds good.

**Comment by dselivanov** [comment]
No, it is not possible - Rserve creates a fork for each connection. On windows everything happens in a main R process.

**Comment by Hong-Revo** [comment]
Ta. It would probably be good to mention this limitation in the docs -- the README says that RestRserve is parallel by design, but not that it's limited to Unices.

**Comment by dselivanov** [comment]
Well, it mention that it creates a fork for each request with Rserve backend. But yes, may be it is not super clear - I will update readme.
