### ISSUE TITLE
more explicit examples on ML prediction api with more guidance

### ISSUE THREAD

**Issue by KnutJaegersberg** [rexyai/RestRserve#120]
Great lib, deployed it a brief while ago first time instead of opencpu (works much better with reticulate and pointer objects as fasttext models). 
Found it a bit difficult to navigate different examples to get to where I wanted to be. Also restrserve requires a bit more upfront knowledge about restapis than opencpu, where you kind of  just build the package and done. 
I like the freedom and (percieved) architectural simplicity of restrserve over opencpu (I feel more in control), but for a fresh new user, the learning curve feels steeper then for say plumber (but restrserve is also much more powerful). More explicit guidance about the type of applications and when and where you have to specifify things to get those running would be awesome. I mean you can get it if you just read the example code and think about it, but it can be more simple for new users for say a typical use case as a ML prediction api. The examples are good on this one,but require a bit more knowledge than may be handy for a starter or say plumber convert. Opencpu is also a bit more complex but has more documentation. Restrserve is a great, new and still evolving way for making usable rest apis in R.

**Comment by dselivanov** [comment]
@KnutJaegersberg thanks for feedback. Right place is to put it to #109

**Comment by dselivanov** [comment]
@KnutJaegersberg also contributions to documentation are always appreciated - feel free to draft a PR, we will support.
