### ISSUE TITLE
Easiest way to tryout on cloud server?

### ISSUE THREAD

**Issue by rdatasculptor** [rexyai/RestRserve#121]
On my local machine all works very well! Now I would like to try RestRserve on a cloud server. Can you advise me in the easiest way to tryout? Is there a trial version of somekind that I can use?

**Comment by dselivanov** [comment]
Most of the cloud providers provide free tier plan. Easiest way to try to start app in a cloud is to create a docker image and launch it in a cloud. Either using virtual machine or managed container service.

**Comment by rdatasculptor** [comment]
maybe it will help others, this blog was very useful in setting up an rstudio instance on aws: https://towardsdatascience.com/how-to-run-rstudio-on-aws-in-under-3-minutes-for-free-65f8d0b6ccda

I haven't managed to start a restrserve api, but I guess that's a matter of time now.
