### ISSUE TITLE
[BUG] short bug description 

### ISSUE THREAD

**Issue by mrchypark** [rexyai/RestRserve#124]
### Reporting an Issue
Make use of the *Preview* tab just above!

### Before filing an issue
Please ensure that you:
- searched existing [GitHub issues](https://github.com/rexyai/RestRserve/issues) which can be searched among open and closed ones;
- read the [Contributing](https://github.com/rexyai/RestRserve/blob/master/CONTRIBUTING.md) page for details on preferred reporting and style;

### To Reproduce
Please provide a **minimal** example. 'minimal' generally means that example should not use any packages except `RestRserve`. If you are not sure what 'minimal reproducible example' is, please consult [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example). **We appreciate your time to make a bug report.**

For example:
```r
app <- Application$new()

app$logger$set_log_level("all")

app$add_post(
  path = "/",
  FUN = function(req, res){
    res$set_body(req$body)
  }
)

backend = BackendRserve$new()
backend$start(app, http_port = 5000, encoding = "utf8")
```

### Expected behavior

I just try simple json in, json out.

### Environment information
Please provide output of the `sessionInfo()` command. 

For example:
```
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux bullseye/sid

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.6.2
```

### Additional context

![image](https://user-images.githubusercontent.com/6179259/73496736-98a52200-43fc-11ea-8281-5724146f354c.png)

```
request = Request$new(
  path = "/",
  method = "POST",
  body = '{"test":"test"}',
  content_type = "application/json"
)

response = app$process_request(request)
cat(response$body)
```

when i try process request, return 200. but curl request is not.

![image](https://user-images.githubusercontent.com/6179259/73496925-f5084180-43fc-11ea-82d2-13a95fa0be7e.png)

**Comment by dselivanov** [comment]
- Please find time to provide reproducible example so we can "copy paste" in into R terminal to find the issue.
- Please fill properly template fields as requested and delete unnecessary information from template

**Comment by mrchypark** [comment]
I'm sorry to un fit issue. I'll try again after closing this.
