### ISSUE TITLE
Error in parse headers(headers) : header contains invalid character.

### ISSUE THREAD

**Issue by AlexandreBeaudoin** [rexyai/RestRserve#132]
It looks like my headers include the underscore character '_' and I get the following error
``` "Error in parse headers(headers) : header contains invalid character." ```

After modifying parse_headers.cpp:
```
bool validate_header_name(const std::string& x) {
  auto check = [&](char c) { return std::isalpha(c) || c == '-' || c == '_'; };
  return std::all_of(x.begin(), x.end(), check);
}
```

I no longer get that error.

**Comment by dselivanov** [comment]
Thanks for reporting! you are right, according to [rfc7230](https://tools.ietf.org/html/rfc7230#section-3.2.6) header name may consists of:

```
     token          = 1*tchar

     tchar          = "!" / "#" / "$" / "%" / "&" / "'" / "*"
                    / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
                    / DIGIT / ALPHA
                    ; any VCHAR, except delimiters
```

**Comment by artemklevtsov** [comment]
Fix in the `dev` branch now.
