### ISSUE TITLE
'Depends' too restricted ?

### ISSUE THREAD

**Issue by sambaala** [rexyai/RestRserve#163]
Hello,

Could you please change the Depends field of DESCRIPTION. 
The current value is "Depends: R (>= 3.6.0)", but your package 
seems working even for older versions of R. Your package would 
reach more R users, those with older R versions.
Here are the current Depends fields of your current dependencies:
	 
| | Package | Depends | Version |
| --- | --- | --- | --- |
| 1 | backports | R (>= 3.0.0) | 1.1.9 |
| 2 | Rcpp | NA | 1.0.5 |
| 3 | Rserve | R (>= 1.5.0) | 1.8-7 |
| 4 | R6 | R (>= 3.0) | 2.4.1 |
| 5 | uuid | R (>= 2.9.0) | 0.1-4 |
| 6 | checkmate | R (>= 3.0.0) | 2.0.0 |
| 7 | mime | NA | 0.9 |
| 8 | jsonlite | methods | 1.7.0 |

I suggest in a following pull request to put "Depends: R (>= 3.0.0)".

Best regards

**Comment by dselivanov** [comment]
Hi @sambaala. We use `errorCondition` for structured exceptions which were introduced in R 3.6.0. There is port of this function in `backports` package, see related discussion in #29. Also it doesn't seem a big deal to copy-paste it here, but I haven't explored all the consequences in details.

**Comment by sambaala** [comment]
Ok @dselivanov, I see. Thank you.
