### ISSUE TITLE
Configuration settings?

### ISSUE THREAD

**Issue by jds-amplify** [rexyai/RestRserve#176]
Hi,

How does one set the number of workers, and which host/ip the server binds to?

Thanks.

**Comment by dselivanov** [comment]
There is no option to specify number of workers - each new  connection is getting assigned with new worker process. You will need to use a proxy/load balancer such as HAproxy to limit number of workers and force connection reuse.

> which host/ip the server binds to?

See very first example in the readme:
```
backend$start(app, http_port = 8080)
```

Also I encourage to check https://github.com/rexyai/RestRserve/blob/master/CONTRIBUTING.md. If you have a question - welcome to [gitter](https://gitter.im/RestRserve/community). This project uses issue tracker only for bug reports.
