### ISSUE TITLE
Automated docker hub builds don't work anymore

### ISSUE THREAD

**Issue by dselivanov** [rexyai/RestRserve#186]
Now required to have at least "team" plan or apply for open source support program -  see [here](https://docs.docker.com/docker-hub/builds/). I've sent submission.

The way Docker Inc started to work with open source community sucks.

**Comment by dselivanov** [comment]
Almost a month already and no response from docker inc

**Comment by s-u** [comment]
I would not rely on a company that is trying to kill all open source support. Just migrate to GitHub Actions and push for now, see e.g.: https://nu12.medium.com/migrating-docker-autobuild-to-github-actions-74945aac1b79

In the long run I would see the world moving to [podman](https://podman.io/) instead and creating a new open source repo, so I would keep the eyes open and wean off Docker.
