### ISSUE TITLE
error creating database (mongolite) connection in handler

### ISSUE THREAD

**Issue by ncullen93** [rexyai/RestRserve#205]
Creating a global mongolite db connection and then trying to grab records in a GET handler works the first time but then leads to a segfault error any subsequent requests. So, I tried to do the recommended thing of creating a db connection in each request. However, for mongo this leads to the following error:

```
objc[2671]: +[NSNumber initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

Not sure if this is on mongolite's side, but it would be nice to at least see an example or hear from others who have made some kind of database solution work with RestRserve.

Basic reprex:

```R
library(RestRserve)
library(mongolite)

fetch_models_handler <- function(req, res) {
  conn <- mongolite::mongo(collection, db, url)
 # then, eventually make a find() call and disconnect
 # adding conn$disconnect() doesnt help
}

app = Application$new(
  content_type = "application/json"
)

app$add_get(
  path = "/fetchModels",
  FUN = fetch_models_handler
)

backend = BackendRserve$new()
backend$start(app, http_port = 8080)
```

**Comment by dselivanov** [comment]
Could you please provide reproducible example for postgres? I've used
postgresql with restrserve in production for years without issue

**Comment by s-u** [comment]
@ncullen93 the error suggests the you were running it on macOS in an interactive session - or that you included a package which tried to initialize interactive session/run-time. Please make sure the app is started via `Rscript` on the command line and not in any GUI.
