### ISSUE TITLE
Issue with column oriented json encoding

### ISSUE THREAD

**Issue by StianBerger** [rexyai/RestRserve#218]
I am trying to create a rest app that outputs server side rendered plotly plots.
When i pass the built plot through response object with json content type, it somehow transforms the data in the plotly object to columnar form. (Instead of being an array of objects, it becomes objects of arrays.)
I have scratched my head a lot trying to figure out why this happens, and came across this:
https://github.com/rexyai/RestRserve/blob/c24c92bf91975e7c8a3f435f452002766616bfc0/R/json.R#L19

Could we have a way of configuring the dataframe='columns' parameter?

As of now, I found a workaround by setting custom encoder on the response object - and I can live with that.
I think that this can bite others as well though.

Thanks for a great package

**Comment by dselivanov** [comment]
Hi @StianBerger 
This is by design. And your approach with setting custom serializer/encoder is a correct approach to amend default behavior.
