### ISSUE TITLE
Any plan for pushing into cran soon?

### ISSUE THREAD

**Issue by luckys59** [rexyai/RestRserve#99]
Thank you for writing such a nice utility for concurrent R service. I wanted to check if there is any plan for pushing it cran?

**Comment by dselivanov** [comment]
Definitely! Hopefully within 1 month.

пт, 25 окт. 2019 г., 16:50 luckys59 <notifications@github.com>:

**Comment by luckys59** [comment]
Thanks for the quick response. Much appreciated!

**Comment by Hong-Revo** [comment]
I was just about to ask this very question. Looking forward to seeing this great piece of work on CRAN.

**Comment by luckys59** [comment]
Hi @dselivanov , Looking forward for your help in pushing this awesome work into CRAN. We are using from little over a month and absolutely loved it.

Thanks a lot once again!

**Comment by dselivanov** [comment]
@luckys59 appreciate if you could share with us your experience in #109 . For example which parts feel not intuitive, what can be improved in documentation, etc.

**Comment by luckys59** [comment]
@dselivanov, we are badly waiting for RestRserve into CRAN. Please publish the current stable

**Comment by dselivanov** [comment]
I've submitted pkg for CRAN review in the beginning of Feb. So far I've reiterated several times addressing CRAN team concerns. Hopefully will be published very soon.

**Comment by dselivanov** [comment]
https://cran.r-project.org/web/packages/RestRserve/

**Comment by lorenzwalthert** [comment]
Where can I retweet @dselivanov? 😄

**Comment by dselivanov** [comment]
I'm drafting a release announcement. I will post a link here once it is
done. May take couple of days.
